"""Fix target_tags default

Revision ID: 18f64b9f1371
Revises: 94228414b767
Create Date: 2026-07-08 17:17:13.133980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18f64b9f1371'
down_revision: Union[str, Sequence[str], None] = '94228414b767'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('schedules', 'target_tags', server_default='[]')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('schedules', 'target_tags', server_default=None)
    # ### end Alembic commands ###
