"""Add target_tags

Revision ID: 94228414b767
Revises: b6827e9b4cf8
Create Date: 2026-07-08 17:13:13.305247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '94228414b767'
down_revision: Union[str, Sequence[str], None] = 'b6827e9b4cf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedules', sa.Column('target_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.alter_column('schedules', 'test_definition_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('schedules', 'test_definition_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('schedules', 'target_tags')
    # ### end Alembic commands ###
